### ISSUE TITLE
Which terminal plugin is the one in the photo(this is from nvim-tree.lua)

### ISSUE THREAD

**Issue by samrath2007** [kyazdani42/dotfiles#1]
![image](https://user-images.githubusercontent.com/69572668/122438213-19e06300-cfb8-11eb-9ca5-d21871c58892.png)

**Comment by kyazdani42** [comment]
that's a very good question, this screenshot belongs to @akinsho

**Comment by akinsho** [comment]
It's a terminal plugin I made called https://github.com/akinsho/nvim-toggleterm.lua
